spring:
  application.name: GB OAuth Demo

logging:
  level:
    ROOT: INFO
    org.springframework.security: DEBUG
    com.glad.oauth: DEBUG
  pattern.console: "%d{HH:mm:ss} %-5level %logger{36} : %msg%n"


spring.security.oauth2.client:
  registration:
    # Predefined Google, GitHub, Facebook, and Okta
    facebook:
      # ex: https://github.com/eugenp/tutorials/blob/master/spring-social-login/src/main/resources/application.properties
      client-id: your-facebook-client-id-here
      client-secret: your-facebook-client-secret-here
    github:
      client-id: your-github-client-id-here
      client-secret: your-github-client-secret-here
    google:
      client-id: your-google-client-id-here
      client-secret: your-google-client-secret-here
    #your-provider-id:
    gbokta:
      client-name: Custom Provider Okta
      client-id: your-okta-client-id-here
      client-secret: your-okta-client-secret-here
      authorization-grant-type: authorization_code
      client-authentication-method: post
      redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
      scope: openid, profile
  provider:
    #your-provider-id:
    gbokta:
      authorization-uri: https://your-okta-domain.oktapreview.com/oauth2/v1/authorize
      token-uri: https://your-okta-domain.oktapreview.com/oauth2/v1/token
      user-info-uri: https://your-okta-domain.oktapreview.com/oauth2/v1/userinfo
      jwk-set-uri: https://your-okta-domain.oktapreview.com/oauth2/v1/keys
      user-name-attribute: sub
