spring:
  application.name: GB OAuth Demo

logging:
  level:
    ROOT: INFO
    org.springframework.security: DEBUG
    com.glad.oauth: DEBUG
  pattern.console: "%d{HH:mm:ss} %-5level %logger{36} : %msg%n"


spring.security.oauth2.client:
  registration:
    # Predefined Google, GitHub, Facebook, and Okta
    facebook:
      # ex: https://github.com/eugenp/tutorials/blob/master/spring-social-login/src/main/resources/application.properties
      client-id: your-facebook-client-id-here
      client-secret: your-facebook-client-secret-here
    github:
      client-id: your-github-client-id-here
      client-secret: your-github-client-secret-here
    #your-provider-id:
    gbokta:
      client-name: Custom Provider Demo [Okta]
      client-id: your-okta-client-id-here
      client-secret: your-okta-client-secret-here
      authorization-grant-type: authorization_code
      client-authentication-method: post
      redirect-uri-template: http://gb-oauth-demo.com:8080/login/oauth2/code/gbokta
      scope: openid profile
  provider:
    #your-provider-id:
    gbokta:
      authorization-uri: https://dev-142331.oktapreview.com/oauth2/v1/authorize
      token-uri: https://dev-142331.oktapreview.com/oauth2/v1/token
      user-info-uri: https://dev-142331.oktapreview.com/oauth2/v1/userinfo
      user-name-attribute: sub
      jwk-set-uri: https://dev-142331.oktapreview.com/oauth2/v1/keys
